[package]
name = "mkpki"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
argh = "0.1.13"
bitvec = "1.0.1"
bytes = "1.10.1"
chrono = "0.4.42"
num-bigint = "0.4.6"
num-traits = "0.2.19"
pem-rfc7468 = "0.7.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rasn = "0.28.0"
rasn-pkix = "0.28.0"
rsa = "0.9.8"
sha2 = "0.10.9"

[profile.dev]
opt-level = 3
